$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Train model with diabetes data

display_name: diabetes-train-pipeline
experiment_name: diabetes-train-pipeline
jobs:
  train:
    type: command
    code: src
    command: >-
      python train-mlflow.py --reg_rate ${{inputs.reg_rate}} --training_data ${{inputs.training_data}}

    inputs:
      training_data:
        type: uri_folder
        path: azureml:diabetes-dev-folder:1
      reg_rate: 0.01
    environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
    compute: azureml:cpu-cluster
