name: Trunkbased development

on: [pull_request, workflow_dispatch]

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
