name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml --version 2.4.1 -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Configure default azure ml workspace
        run: az configure --defaults group=${{secrets.GROUP}} workspace=${{secrets.WORKSPACE}} location=${{secrets.LOCATION}}
      - name: Model training
        run: az ml job create -f job-dev.yml --stream
        working-directory: src

  train-prod:
    runs-on: ubuntu-latest
    environment: production
    needs: train-dev
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml --version 2.4.1 -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Configure default azure ml workspace
        run: az configure --defaults group=${{secrets.GROUP}} workspace=${{secrets.WORKSPACE}} location=${{secrets.LOCATION}}
      - name: Model training
        run: az ml job create -f job-prod.yml --stream
        working-directory: src
