name: Trigger GHA

on:
  repository_dispatch:
    types: [deploy_pipeline_action]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{secrets.AZURE_CREDENTIALS}}"
      - name: Echo
        run: |
          echo ${{github.event.client_payload.model_name}}
          echo ${{github.event.client_payload.model_version}}
