name: Trigger GHA

on:
  repository_dispatch:
    types: [deploy_pipeline_action]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml --version 2.4.1 -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Echo
        run: |
          echo ${{github.event.client_payload.model_name}}
          echo ${{github.event.client_payload.model_version}}
