name: Trunkbased development

on: [pull_request]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml --version 2.4.1 -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Placeholder
        run: |
          echo "Will add code checkes here in the next challenge"
